# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - essays.md
  - log.md
  - r.md
  - ref.md
  - about.md

footer: '&copy; 2021 - <a href="https://github.com/0x68h/" target="_blank">0x68h</a> All Rights Reserved.'

#style: light # dark (default) or light
style: light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
