# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: '&copy; 2019 - <a href="https://github.com/hec0/" target="_blank">hec0</a> All Rights Reserved.'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
