# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - essays.md
  - about.md

footer: '&copy; 2020 - <a href="https://github.com/hr0x/" target="_blank">hr0x</a> All Rights Reserved.'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
