# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - essays.md
  - about.md

footer: '&copy; 2021 - <a href="https://github.com/hel88/" target="_blank">hel88</a> All Rights Reserved.'

#style: light # dark (default) or light
style: hacker
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
